### ISSUE TITLE
Generate DNIs

### ISSUE THREAD

**Issue by lluis-iati** [joanTrave/spanish_dni#1]
Hello Joan,

First, thank you for creating such a great library; it has been incredibly useful for my projects. I have a suggestion to make it even better. Currently, the library generates a lot of useful data, but I noticed that it does not generate valid DNIs (Documento Nacional de Identidad).

Adding this feature would be very beneficial, especially for those of us who need to work with valid DNI data in our frameworks and repositories. It would save time and ensure more accurate testing and data validation processes.

Please consider this suggestion. Thank you for your hard work and dedication to improving this library.

Best regards,  
Luigi

**Comment by joanTrave** [comment]
Hello Luigi,

First of all, I want to thank you for your interest in this library. I really appreciate the effort you have invested in opening this issue and therefore, after evaluating the fit of your proposal, I have implemented the feature you suggest. To use it, please install version 1.0.3 of this library.

You can find examples on the generation of random DNI in the README.md file (in the project description), or on the PyPI page in version 1.0.3 of this library.

Please, do not hesitate about reporting any issue you could find or suggest any new feature you could consider relevant.

Best regards,

Joan

**Comment by lluis-iati** [comment]
Hello Joan,

Nice one! thanks a bunch, mate!
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM29uMGl4dm03NjY0Zm41eHExcGp3YnAxZmF3MjZyaTV0dmlpdGpzdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKDgHIAB13Eq0Ja/giphy.gif)
